/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const PlanTier = IDL.Variant({
  'pro' : IDL.Null,
  'enterprise' : IDL.Null,
  'free' : IDL.Null,
});
export const BillingPeriod = IDL.Variant({
  'annual' : IDL.Null,
  'monthly' : IDL.Null,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
  'succeeded' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'amountCents' : IDL.Nat,
  'currency' : IDL.Text,
  'stripePaymentIntentId' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : InvoiceStatus,
  'userId' : UserId,
  'downloadData' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'amountCents' : IDL.Nat,
  'stripeInvoiceId' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'paidAt' : IDL.Opt(Timestamp),
});
export const BillingAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'customer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'billingAddress' : IDL.Opt(BillingAddress),
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'pastDue' : IDL.Null,
  'trialing' : IDL.Null,
});
export const Subscription = IDL.Record({
  'status' : SubscriptionStatus,
  'nextBillingDate' : Timestamp,
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'tier' : PlanTier,
  'billingPeriod' : BillingPeriod,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'startDate' : Timestamp,
});
export const UsageRecord = IDL.Record({
  'month' : IDL.Nat,
  'userId' : UserId,
  'year' : IDL.Nat,
  'apiCallCount' : IDL.Nat,
});
export const PlanConfig = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'annualPriceCents' : IDL.Nat,
  'monthlyPriceCents' : IDL.Nat,
  'name' : IDL.Text,
  'tier' : PlanTier,
  'description' : IDL.Text,
  'apiCallLimit' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TeamMemberStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'suspended' : IDL.Null,
});
export const TeamMember = IDL.Record({
  'status' : TeamMemberStatus,
  'joinDate' : Timestamp,
  'name' : IDL.Text,
  'role' : UserRole,
  'invitedBy' : UserId,
  'email' : IDL.Text,
  'principalId' : UserId,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminSetSubscription' : IDL.Func([UserId, PlanTier, BillingPeriod], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelMySubscription' : IDL.Func([], [], []),
  'confirmPayment' : IDL.Func(
      [IDL.Text, PlanTier, BillingPeriod],
      [Transaction],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
  'getMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getMySubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getMyUsage' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(UsageRecord)],
      ['query'],
    ),
  'getPlans' : IDL.Func([], [IDL.Vec(PlanConfig)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserSubscription' : IDL.Func(
      [UserId],
      [IDL.Opt(Subscription)],
      ['query'],
    ),
  'getUserUsage' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [IDL.Opt(UsageRecord)],
      ['query'],
    ),
  'inviteTeamMember' : IDL.Func([UserId, IDL.Text, IDL.Text, UserRole], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'recordApiCall' : IDL.Func([], [], []),
  'removeTeamMember' : IDL.Func([UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserRole' : IDL.Func([UserId, UserRole], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateTeamMemberStatus' : IDL.Func([UserId, TeamMemberStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const PlanTier = IDL.Variant({
    'pro' : IDL.Null,
    'enterprise' : IDL.Null,
    'free' : IDL.Null,
  });
  const BillingPeriod = IDL.Variant({
    'annual' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
    'succeeded' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'amountCents' : IDL.Nat,
    'currency' : IDL.Text,
    'stripePaymentIntentId' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : InvoiceStatus,
    'userId' : UserId,
    'downloadData' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'amountCents' : IDL.Nat,
    'stripeInvoiceId' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'paidAt' : IDL.Opt(Timestamp),
  });
  const BillingAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'customer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'billingAddress' : IDL.Opt(BillingAddress),
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'pastDue' : IDL.Null,
    'trialing' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'status' : SubscriptionStatus,
    'nextBillingDate' : Timestamp,
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'tier' : PlanTier,
    'billingPeriod' : BillingPeriod,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'startDate' : Timestamp,
  });
  const UsageRecord = IDL.Record({
    'month' : IDL.Nat,
    'userId' : UserId,
    'year' : IDL.Nat,
    'apiCallCount' : IDL.Nat,
  });
  const PlanConfig = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'annualPriceCents' : IDL.Nat,
    'monthlyPriceCents' : IDL.Nat,
    'name' : IDL.Text,
    'tier' : PlanTier,
    'description' : IDL.Text,
    'apiCallLimit' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TeamMemberStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const TeamMember = IDL.Record({
    'status' : TeamMemberStatus,
    'joinDate' : Timestamp,
    'name' : IDL.Text,
    'role' : UserRole,
    'invitedBy' : UserId,
    'email' : IDL.Text,
    'principalId' : UserId,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminSetSubscription' : IDL.Func(
        [UserId, PlanTier, BillingPeriod],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelMySubscription' : IDL.Func([], [], []),
    'confirmPayment' : IDL.Func(
        [IDL.Text, PlanTier, BillingPeriod],
        [Transaction],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
    'getMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getMySubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getMyUsage' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(UsageRecord)],
        ['query'],
      ),
    'getPlans' : IDL.Func([], [IDL.Vec(PlanConfig)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserSubscription' : IDL.Func(
        [UserId],
        [IDL.Opt(Subscription)],
        ['query'],
      ),
    'getUserUsage' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [IDL.Opt(UsageRecord)],
        ['query'],
      ),
    'inviteTeamMember' : IDL.Func(
        [UserId, IDL.Text, IDL.Text, UserRole],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'recordApiCall' : IDL.Func([], [], []),
    'removeTeamMember' : IDL.Func([UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserRole' : IDL.Func([UserId, UserRole], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateTeamMemberStatus' : IDL.Func([UserId, TeamMemberStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };