/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillingAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'line1' : string,
  'line2' : [] | [string],
  'state' : [] | [string],
}
export type BillingPeriod = { 'annual' : null } |
  { 'monthly' : null };
export interface Invoice {
  'id' : string,
  'status' : InvoiceStatus,
  'userId' : UserId,
  'downloadData' : [] | [string],
  'createdAt' : Timestamp,
  'description' : string,
  'amountCents' : bigint,
  'stripeInvoiceId' : [] | [string],
  'currency' : string,
  'paidAt' : [] | [Timestamp],
}
export type InvoiceStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface PlanConfig {
  'features' : Array<string>,
  'annualPriceCents' : bigint,
  'monthlyPriceCents' : bigint,
  'name' : string,
  'tier' : PlanTier,
  'description' : string,
  'apiCallLimit' : bigint,
}
export type PlanTier = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'free' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'status' : SubscriptionStatus,
  'nextBillingDate' : Timestamp,
  'stripeSubscriptionId' : [] | [string],
  'userId' : UserId,
  'tier' : PlanTier,
  'billingPeriod' : BillingPeriod,
  'stripeCustomerId' : [] | [string],
  'startDate' : Timestamp,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'pastDue' : null } |
  { 'trialing' : null };
export interface TeamMember {
  'status' : TeamMemberStatus,
  'joinDate' : Timestamp,
  'name' : string,
  'role' : UserRole,
  'invitedBy' : UserId,
  'email' : string,
  'principalId' : UserId,
}
export type TeamMemberStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'suspended' : null };
export type Timestamp = bigint;
export interface Transaction {
  'id' : string,
  'status' : TransactionStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'amountCents' : bigint,
  'currency' : string,
  'stripePaymentIntentId' : string,
}
export type TransactionStatus = { 'pending' : null } |
  { 'refunded' : null } |
  { 'failed' : null } |
  { 'succeeded' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UsageRecord {
  'month' : bigint,
  'userId' : UserId,
  'year' : bigint,
  'apiCallCount' : bigint,
}
export type UserId = Principal;
export interface UserProfile {
  'billingAddress' : [] | [BillingAddress],
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'customer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminSetSubscription' : ActorMethod<
    [UserId, PlanTier, BillingPeriod],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelMySubscription' : ActorMethod<[], undefined>,
  'confirmPayment' : ActorMethod<
    [string, PlanTier, BillingPeriod],
    Transaction
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyInvoice' : ActorMethod<[string], [] | [Invoice]>,
  'getMyInvoices' : ActorMethod<[], Array<Invoice>>,
  'getMySubscription' : ActorMethod<[], [] | [Subscription]>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getMyUsage' : ActorMethod<[bigint, bigint], [] | [UsageRecord]>,
  'getPlans' : ActorMethod<[], Array<PlanConfig>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserSubscription' : ActorMethod<[UserId], [] | [Subscription]>,
  'getUserUsage' : ActorMethod<[UserId, bigint, bigint], [] | [UsageRecord]>,
  'inviteTeamMember' : ActorMethod<
    [UserId, string, string, UserRole],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'recordApiCall' : ActorMethod<[], undefined>,
  'removeTeamMember' : ActorMethod<[UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserRole' : ActorMethod<[UserId, UserRole], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateTeamMemberStatus' : ActorMethod<[UserId, TeamMemberStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];