/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface BillingAddress {
    country: string;
    city: string;
    postalCode: string;
    line1: string;
    line2?: string;
    state?: string;
}
export interface UsageRecord {
    month: bigint;
    userId: UserId;
    year: bigint;
    apiCallCount: bigint;
}
export interface Invoice {
    id: string;
    status: InvoiceStatus;
    userId: UserId;
    downloadData?: string;
    createdAt: Timestamp;
    description: string;
    amountCents: bigint;
    stripeInvoiceId?: string;
    currency: string;
    paidAt?: Timestamp;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Transaction {
    id: string;
    status: TransactionStatus;
    userId: UserId;
    createdAt: Timestamp;
    description: string;
    amountCents: bigint;
    currency: string;
    stripePaymentIntentId: string;
}
export type UserId = Principal;
export interface Subscription {
    status: SubscriptionStatus;
    nextBillingDate: Timestamp;
    stripeSubscriptionId?: string;
    userId: UserId;
    tier: PlanTier;
    billingPeriod: BillingPeriod;
    stripeCustomerId?: string;
    startDate: Timestamp;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface PlanConfig {
    features: Array<string>;
    annualPriceCents: bigint;
    monthlyPriceCents: bigint;
    name: string;
    tier: PlanTier;
    description: string;
    apiCallLimit: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface TeamMember {
    status: TeamMemberStatus;
    joinDate: Timestamp;
    name: string;
    role: UserRole;
    invitedBy: UserId;
    email: string;
    principalId: UserId;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    billingAddress?: BillingAddress;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}
export enum BillingPeriod {
    annual = "annual",
    monthly = "monthly"
}
export enum InvoiceStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum PlanTier {
    pro = "pro",
    enterprise = "enterprise",
    free = "free"
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled",
    pastDue = "pastDue",
    trialing = "trialing"
}
export enum TeamMemberStatus {
    active = "active",
    pending = "pending",
    suspended = "suspended"
}
export enum TransactionStatus {
    pending = "pending",
    refunded = "refunded",
    failed = "failed",
    succeeded = "succeeded"
}
export enum UserRole {
    manager = "manager",
    admin = "admin",
    customer = "customer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    adminSetSubscription(userId: UserId, tier: PlanTier, billingPeriod: BillingPeriod): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    cancelMySubscription(): Promise<void>;
    confirmPayment(sessionId: string, tier: PlanTier, billingPeriod: BillingPeriod): Promise<Transaction>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getMyInvoice(invoiceId: string): Promise<Invoice | null>;
    getMyInvoices(): Promise<Array<Invoice>>;
    getMySubscription(): Promise<Subscription | null>;
    getMyTransactions(): Promise<Array<Transaction>>;
    getMyUsage(year: bigint, month: bigint): Promise<UsageRecord | null>;
    getPlans(): Promise<Array<PlanConfig>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTeamMembers(): Promise<Array<TeamMember>>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    getUserSubscription(userId: UserId): Promise<Subscription | null>;
    getUserUsage(userId: UserId, year: bigint, month: bigint): Promise<UsageRecord | null>;
    inviteTeamMember(memberId: UserId, name: string, email: string, role: UserRole): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllUsers(): Promise<Array<UserProfile>>;
    recordApiCall(): Promise<void>;
    removeTeamMember(memberId: UserId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setUserRole(userId: UserId, role: UserRole): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateTeamMemberStatus(memberId: UserId, status: TeamMemberStatus): Promise<void>;
}
import type { BillingAddress as _BillingAddress, BillingPeriod as _BillingPeriod, Invoice as _Invoice, InvoiceStatus as _InvoiceStatus, PlanConfig as _PlanConfig, PlanTier as _PlanTier, StripeSessionStatus as _StripeSessionStatus, Subscription as _Subscription, SubscriptionStatus as _SubscriptionStatus, TeamMember as _TeamMember, TeamMemberStatus as _TeamMemberStatus, Timestamp as _Timestamp, Transaction as _Transaction, TransactionStatus as _TransactionStatus, UsageRecord as _UsageRecord, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminSetSubscription(arg0: UserId, arg1: PlanTier, arg2: BillingPeriod): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetSubscription(arg0, to_candid_PlanTier_n1(this._uploadFile, this._downloadFile, arg1), to_candid_BillingPeriod_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetSubscription(arg0, to_candid_PlanTier_n1(this._uploadFile, this._downloadFile, arg1), to_candid_BillingPeriod_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelMySubscription(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelMySubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelMySubscription();
            return result;
        }
    }
    async confirmPayment(arg0: string, arg1: PlanTier, arg2: BillingPeriod): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0, to_candid_PlanTier_n1(this._uploadFile, this._downloadFile, arg1), to_candid_BillingPeriod_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Transaction_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0, to_candid_PlanTier_n1(this._uploadFile, this._downloadFile, arg1), to_candid_BillingPeriod_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Transaction_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInvoice(arg0: string): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInvoice(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInvoice(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInvoices();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInvoices();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscription(): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscription();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscription();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyUsage(arg0: bigint, arg1: bigint): Promise<UsageRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUsage(arg0, arg1);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUsage(arg0, arg1);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlans(): Promise<Array<PlanConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlans();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlans();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMembers();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMembers();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSubscription(arg0: UserId): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubscription(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubscription(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserUsage(arg0: UserId, arg1: bigint, arg2: bigint): Promise<UsageRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserUsage(arg0, arg1, arg2);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserUsage(arg0, arg1, arg2);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async inviteTeamMember(arg0: UserId, arg1: string, arg2: string, arg3: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteTeamMember(arg0, arg1, arg2, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteTeamMember(arg0, arg1, arg2, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordApiCall(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordApiCall();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordApiCall();
            return result;
        }
    }
    async removeTeamMember(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTeamMember(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setUserRole(arg0: UserId, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateTeamMemberStatus(arg0: UserId, arg1: TeamMemberStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMemberStatus(arg0, to_candid_TeamMemberStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMemberStatus(arg0, to_candid_TeamMemberStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BillingAddress_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingAddress): BillingAddress {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_BillingPeriod_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingPeriod): BillingPeriod {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PlanConfig_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanConfig): PlanConfig {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PlanTier_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanTier): PlanTier {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_TeamMemberStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMemberStatus): TeamMemberStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_TeamMember_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMember): TeamMember {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BillingAddress]): BillingAddress | null {
    return value.length === 0 ? null : from_candid_BillingAddress_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UsageRecord]): UsageRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _InvoiceStatus;
    userId: _UserId;
    downloadData: [] | [string];
    createdAt: _Timestamp;
    description: string;
    amountCents: bigint;
    stripeInvoiceId: [] | [string];
    currency: string;
    paidAt: [] | [_Timestamp];
}): {
    id: string;
    status: InvoiceStatus;
    userId: UserId;
    downloadData?: string;
    createdAt: Timestamp;
    description: string;
    amountCents: bigint;
    stripeInvoiceId?: string;
    currency: string;
    paidAt?: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n14(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        downloadData: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.downloadData)),
        createdAt: value.createdAt,
        description: value.description,
        amountCents: value.amountCents,
        stripeInvoiceId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.stripeInvoiceId)),
        currency: value.currency,
        paidAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.paidAt))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    billingAddress: [] | [_BillingAddress];
    userId: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
}): {
    billingAddress?: BillingAddress;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
} {
    return {
        billingAddress: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.billingAddress)),
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n25(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    city: string;
    postalCode: string;
    line1: string;
    line2: [] | [string];
    state: [] | [string];
}): {
    country: string;
    city: string;
    postalCode: string;
    line1: string;
    line2?: string;
    state?: string;
} {
    return {
        country: value.country,
        city: value.city,
        postalCode: value.postalCode,
        line1: value.line1,
        line2: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.line2)),
        state: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.state))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubscriptionStatus;
    nextBillingDate: _Timestamp;
    stripeSubscriptionId: [] | [string];
    userId: _UserId;
    tier: _PlanTier;
    billingPeriod: _BillingPeriod;
    stripeCustomerId: [] | [string];
    startDate: _Timestamp;
}): {
    status: SubscriptionStatus;
    nextBillingDate: Timestamp;
    stripeSubscriptionId?: string;
    userId: UserId;
    tier: PlanTier;
    billingPeriod: BillingPeriod;
    stripeCustomerId?: string;
    startDate: Timestamp;
} {
    return {
        status: from_candid_SubscriptionStatus_n33(_uploadFile, _downloadFile, value.status),
        nextBillingDate: value.nextBillingDate,
        stripeSubscriptionId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.stripeSubscriptionId)),
        userId: value.userId,
        tier: from_candid_PlanTier_n35(_uploadFile, _downloadFile, value.tier),
        billingPeriod: from_candid_BillingPeriod_n37(_uploadFile, _downloadFile, value.billingPeriod),
        stripeCustomerId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.stripeCustomerId)),
        startDate: value.startDate
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    features: Array<string>;
    annualPriceCents: bigint;
    monthlyPriceCents: bigint;
    name: string;
    tier: _PlanTier;
    description: string;
    apiCallLimit: bigint;
}): {
    features: Array<string>;
    annualPriceCents: bigint;
    monthlyPriceCents: bigint;
    name: string;
    tier: PlanTier;
    description: string;
    apiCallLimit: bigint;
} {
    return {
        features: value.features,
        annualPriceCents: value.annualPriceCents,
        monthlyPriceCents: value.monthlyPriceCents,
        name: value.name,
        tier: from_candid_PlanTier_n35(_uploadFile, _downloadFile, value.tier),
        description: value.description,
        apiCallLimit: value.apiCallLimit
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TeamMemberStatus;
    joinDate: _Timestamp;
    name: string;
    role: _UserRole;
    invitedBy: _UserId;
    email: string;
    principalId: _UserId;
}): {
    status: TeamMemberStatus;
    joinDate: Timestamp;
    name: string;
    role: UserRole;
    invitedBy: UserId;
    email: string;
    principalId: UserId;
} {
    return {
        status: from_candid_TeamMemberStatus_n49(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: from_candid_UserRole_n25(_uploadFile, _downloadFile, value.role),
        invitedBy: value.invitedBy,
        email: value.email,
        principalId: value.principalId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TransactionStatus;
    userId: _UserId;
    createdAt: _Timestamp;
    description: string;
    amountCents: bigint;
    currency: string;
    stripePaymentIntentId: string;
}): {
    id: string;
    status: TransactionStatus;
    userId: UserId;
    createdAt: Timestamp;
    description: string;
    amountCents: bigint;
    currency: string;
    stripePaymentIntentId: string;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n9(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        description: value.description,
        amountCents: value.amountCents,
        currency: value.currency,
        stripePaymentIntentId: value.stripePaymentIntentId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    refunded: null;
} | {
    failed: null;
} | {
    succeeded: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "refunded" in value ? TransactionStatus.refunded : "failed" in value ? TransactionStatus.failed : "succeeded" in value ? TransactionStatus.succeeded : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): InvoiceStatus {
    return "pending" in value ? InvoiceStatus.pending : "paid" in value ? InvoiceStatus.paid : "refunded" in value ? InvoiceStatus.refunded : "failed" in value ? InvoiceStatus.failed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    customer: null;
}): UserRole {
    return "manager" in value ? UserRole.manager : "admin" in value ? UserRole.admin : "customer" in value ? UserRole.customer : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    pastDue: null;
} | {
    trialing: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : "pastDue" in value ? SubscriptionStatus.pastDue : "trialing" in value ? SubscriptionStatus.trialing : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    enterprise: null;
} | {
    free: null;
}): PlanTier {
    return "pro" in value ? PlanTier.pro : "enterprise" in value ? PlanTier.enterprise : "free" in value ? PlanTier.free : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annual: null;
} | {
    monthly: null;
}): BillingPeriod {
    return "annual" in value ? BillingPeriod.annual : "monthly" in value ? BillingPeriod.monthly : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n45(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    suspended: null;
}): TeamMemberStatus {
    return "active" in value ? TeamMemberStatus.active : "pending" in value ? TeamMemberStatus.pending : "suspended" in value ? TeamMemberStatus.suspended : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlanConfig>): Array<PlanConfig> {
    return value.map((x)=>from_candid_PlanConfig_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamMember>): Array<TeamMember> {
    return value.map((x)=>from_candid_TeamMember_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n20(_uploadFile, _downloadFile, x));
}
function to_candid_BillingAddress_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingAddress): _BillingAddress {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_BillingPeriod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingPeriod): _BillingPeriod {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PlanTier_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanTier): _PlanTier {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TeamMemberStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamMemberStatus): _TeamMemberStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    billingAddress?: BillingAddress;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}): {
    billingAddress: [] | [_BillingAddress];
    userId: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
} {
    return {
        billingAddress: value.billingAddress ? candid_some(to_candid_BillingAddress_n56(_uploadFile, _downloadFile, value.billingAddress)) : candid_none(),
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n51(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    city: string;
    postalCode: string;
    line1: string;
    line2?: string;
    state?: string;
}): {
    country: string;
    city: string;
    postalCode: string;
    line1: string;
    line2: [] | [string];
    state: [] | [string];
} {
    return {
        country: value.country,
        city: value.city,
        postalCode: value.postalCode,
        line1: value.line1,
        line2: value.line2 ? candid_some(value.line2) : candid_none(),
        state: value.state ? candid_some(value.state) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanTier): {
    pro: null;
} | {
    enterprise: null;
} | {
    free: null;
} {
    return value == PlanTier.pro ? {
        pro: null
    } : value == PlanTier.enterprise ? {
        enterprise: null
    } : value == PlanTier.free ? {
        free: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingPeriod): {
    annual: null;
} | {
    monthly: null;
} {
    return value == BillingPeriod.annual ? {
        annual: null
    } : value == BillingPeriod.monthly ? {
        monthly: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    manager: null;
} | {
    admin: null;
} | {
    customer: null;
} {
    return value == UserRole.manager ? {
        manager: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.customer ? {
        customer: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamMemberStatus): {
    active: null;
} | {
    pending: null;
} | {
    suspended: null;
} {
    return value == TeamMemberStatus.active ? {
        active: null
    } : value == TeamMemberStatus.pending ? {
        pending: null
    } : value == TeamMemberStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
